micro_blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from blog import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='home'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^login/', views.login, name='login'),
    url(r'^about/', views.about, name='about'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^test/', views.test, name='test_feed'),
    url(r'^test_prof/', views.test_user_profile, name='test_user_profile'),
]

urlpatterns += url(r'^(?P<pk>\w+)', views.feed, name='feed'),
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models

# Create your models here.


class User(models.Model):

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    username = models.CharField(max_length=16, unique=True)
    email = models.CharField(default='abc@example.com', unique=True, max_length=75)
    password_hash = models.CharField(max_length=256)
    city = models.CharField(max_length=50, blank=True)
    country = models.CharField(max_length=50, blank=True)
    # post_count = models.IntegerField(default=0)

    def __str__(self):
        return self.username


class Post(models.Model):

    publish_date = models.DateTimeField(auto_now=True)
    content = models.CharField(max_length=150)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-publish_date']

    def __str__(self):
        return self.content

blog/forms.py
from django.forms import ModelForm
from django import forms


class UserSignupForm(forms.Form):

    first_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'autocomplete': 'off'}))
    last_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'autocomplete': 'off'}))
    username = forms.CharField(max_length=16, widget=forms.TextInput(attrs={'autocomplete': 'off'}))
    email = forms.CharField(max_length=75)
    password = forms.CharField(max_length=64, widget=forms.PasswordInput)
    password_confirm = forms.CharField(max_length=64, widget=forms.PasswordInput)


class UserSignupForm2(forms.Form):

    city = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'autocomplete': 'off'}))
    country = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'autocomplete': 'off'}))


class UserLoginForm(forms.Form):

    username = forms.CharField(max_length=16)
    password = forms.CharField(max_length=64, widget=forms.PasswordInput)


class NewPostForm(forms.Form):

    post_content = forms.CharField(max_length=150, widget=forms.Textarea(attrs={'placeholder': "What's on your mind...?"}), label='', )

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import UserSignupForm, UserLoginForm, UserSignupForm2, NewPostForm
from .models import User, Post
from django.contrib.auth.hashers import check_password, make_password
from django.contrib import messages, sessions
from django.contrib.messages import get_messages

# Create your views here.

title_main = 'Micro Blog'


def index(request):
    if request.session.get('remember_user') is not None:
        return redirect('feed', pk=request.session.get('remember_user'))
    if request.session.get('form_success') is not None:
        del request.session['form_success']

    context = {'title_main': title_main, 'title_sub': 'Home'}
    return render(request, 'blog/index.html', context)


def signup(request):
    new_user = User()
    err_list = []
    if request.method == 'POST' and request.session.get('form_success') is None:
        form = UserSignupForm(request.POST)
        if User.objects.filter(username=request.POST['username']).exists():
            err_list.append('username already exists.')
        if User.objects.filter(email=request.POST['email']).exists():
            err_list.append('An account with the entered email already exists.')
        if request.POST['password'] != request.POST['password_confirm']:
            err_list.append('The entered passwords do not match.')
        if len(request.POST['password']) < 6:
            err_list.append('The password is too short. (min. 6 characters')

        if form.is_valid() and len(err_list) == 0:
            new_user.first_name = form.cleaned_data['first_name']
            new_user.last_name = form.cleaned_data['last_name']
            new_user.username = form.cleaned_data['username']
            new_user.email = form.cleaned_data['email']
            p_hash = make_password(form.cleaned_data['password'])
            new_user.password_hash = p_hash
            new_user.save()
            messages.add_message(request, messages.SUCCESS, 'Account created successfully. Log in to continue.')

            request.session['form_success'] = 'true'
            request.session['registered_user'] = new_user.username
            form2 = UserSignupForm2()
            context = {'title_main': title_main, 'title_sub': 'Sign Up', 'form': form2}
            return render(request, 'blog/signup2.html', context)

    elif request.method == 'POST' and request.session.get('form_success') == 'true':
        if request.session['registered_user'] is None:
            return HttpResponse('cookie not found.')
        else:
            user = User.objects.get(username=request.session['registered_user']);
            user.city = request.POST['city']
            user.country = request.POST['country']
            user.save()
            del request.session['registered_user']
            return redirect('login')

    else:
        form = UserSignupForm()
    context = {'title_main': title_main, 'title_sub': 'Sign Up', 'form': form, 'err_list': err_list}
    return render(request, 'blog/signup.html', context)


def login(request):
    form = UserLoginForm()
    msg = get_messages(request)
    err_list = []
    if request.method == 'POST' and User.objects.filter(username=request.POST['username']).exists():
        user = User.objects.get(username=request.POST['username'])
        if check_password(request.POST['password'], user.password_hash):
            request.session['current_user'] = user.username
            if request.POST.get('remember_me', 'off') == 'on':
                request.session['remember_user'] = user.username
            return redirect('feed', pk=user.username)

        else:
            err_list.append('Invalid username and/or password.')
    elif request.method == 'POST' and not User.objects.filter(username=request.POST['username']).exists():
        print('checkbox value: ' + request.POST.get('remember_me', 'off'))
        err_list.append('Invalid username and/or password.')

    else:
        form = UserLoginForm()

    context = {'title_main': title_main, 'title_sub': 'Log In', 'form': form, 'messages': msg, 'err_list': err_list}
    return render(request, 'blog/login.html', context)


def logout(request):
    if request.session.get('remember_user') is not None:
        del request.session['remember_user']
    request.session.flush()
    print(request.session.get('remember_user'))
    return redirect('home')


def about(request):
    return HttpResponse("This is the about page.")


def feed(request, pk):
    post_list= Post.objects.all();
    if request.method == 'POST':
        new_post = Post()
        new_post.content = request.POST['post_content']
        new_post.author = User.objects.get(username=request.session.get('current_user'))
        new_post.save()
        return redirect('feed', pk=request.session.get('current_user'))
        print(new_post.publish_date)
    return render(request, 'blog/feed_base.html', {'user': pk, 'post_list': post_list})


def test(request):
    return render(request, 'test/test_feed.html')
    # return HttpResponse('hello world')


def test_user_profile(request):
    return render(request, 'test/test_user_profile.html')

blog/templates/blog/feed_base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link href="{% static 'css/test/style.css' %}" rel="stylesheet">
{#            <link href="https://fonts.googleapis.com/css?family=Signika" rel="stylesheet">#}
    </head>
    <body>

    <!--header-->
    <div id="header" class="flex">
        <div id="header-logo"><h1><a href="{% url 'home' %}">mBlog</a> </h1></div>
        <div id="dropdown">
            <img id="header-profile-pic" src="{% static 'css/test/ss.png' %}">
            <div class="dropdown-container">
                <div class="dropdown-item"><a href="{% url 'logout' %}">Log out</a></div>
            </div>


        </div>
    </div>

    <!--body-->
    <div id="body" class="flex">

        <!--sidebar-->
        <div id="sidebar">
            <div id="profile-side-container">
                <img id="profile-pic" src="{% static 'css/test/ss.png' %}" alt="profile pic">
                <div class="divider"></div>
                <div id="side-stat-container" class="flex">
                    <p><strong>POSTS </strong>34,236</p>
                    <p><strong>FOLLOWERS </strong>2.5M</p>
                    <p><strong>FOLLOWING </strong>12</p>
                </div>
                    <div id="profile-info" class="container-90">
                        <p><strong>Lives in</strong> Jabalpur, India</p>
                        <p><strong>About </strong> I'm just some guy studying in GGCT.</p>
                    </div>
            </div>

            <div id="side-footer">
                <div class="side-footer-half">
                    <a href="">About</a>
                    <a href="">Help</a>
                    <a href="">Terms</a>
                    <a href="">Privacy Policy</a>
                </div>
                <div class="divider-full"></div>
                <div class="side-footer-half">
                    &copy; 2017 Anchit Shukla
                </div>
            </div>
        </div>


        <!--content-->
        <div id="content">
            <div id="new-post-container">
                <form id="new-post-form" method="post"> {% csrf_token %}
                    <textarea id="id_post_content" name="post_content" placeholder="What's on your mind...?" maxlength="150" rows="10" cols="40"></textarea>
                    <div id="new-post-bottom">
                        <input id="post-btn" type="submit" value="POST" formnovalidate>
                    </div>
                </form>
            </div>

            <div id="post-container">
                {% for post in post_list %}
                    <div class="post flex">
                        <img src="{% static 'css/test/ss.png' %}">
                        <div class="post-content">
                            <div class="post-content-upper flex">
                                <strong>{{ post.author.first_name }} {{ post.author.last_name }}</strong>
                                <p>@{{ post.author }}</p>
                                <p class="post-timestamp">{{ post.publish_date }}</p>
                            </div>
                            <div class="post-content-main">
                                {{ post.content }}
                            </div>
                            <div class="post-lower"></div>
                        </div>
                    </div>
                    <div class="divider-full"></div>
                {% endfor %}
            </div>
        </div>

        <!--aside-->
        <div id="aside"></div>
    </div>

    <!--footer-->
    <div id="footer"></div>
    </body>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/feed.js' %}"></script>
</html>

blog/templates/blog/generic_signup_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title_main }} | {{ title_sub }}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">
{#    <link href="https://fonts.googleapis.com/css?family=Signika" rel="stylesheet">#}
</head>
<body>

<div class="header">
    <div class="header-link"><a href="{% url 'about' %}" class="block">ABOUT</a></div>
    <div class="header-logo"><a href="{% url 'home' %}" class="block">mBlog</a></div>
</div>

<div class="container">
    {% block content %}

    {% endblock %}
</div>
</body>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
{% block scripts %} {% endblock %}
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title_main }} | {{ title_sub }}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <a href="{% url 'test_feed' %}">Test feed</a>
    <a href="{% url 'test_user_profile' %}">Test user profile</a>
    <div class="conatiner-main">
        <h1>Micro Blog</h1>
        <div class="btn-group">
            <div class="btn"><a href="{% url 'login' %}">log in</a></div>
            <div class="btn"><a href="{% url 'signup' %}">sign up</a></div>
        </div>
    </div>

</body>
</html>

blog/templates/blog/login.html
{% extends "blog/generic_signup_login.html" %}

{% block content %}
    <h1>Log In</h1>
    <form method="POST"> {% csrf_token %}
        {% if messages %}
            <div class="success-dialog">
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        {% if err_list %}
        <div class="error-dialog">
            <ul>
            {% for error in err_list %}
                <p>{{ error }}</p>
            {% endfor %}
            </ul>
        </div>
        {% endif %}

        {{ form.as_p }}
        <div id="checkbox-container">
            <input type="checkbox" id="id_remember_me" name="remember_me">
            <span id="check_label">Remember me</span>
        </div>

        <button type="submit" class="submit-btn">Log In >></button>
        <p style="text-align: center; color: white;">or <a id="f-link" href="{% url 'signup' %}">sign up</a> if you don't already have an account. </p>
    </form>
{% endblock %}

blog/templates/blog/signup.html
{% extends "blog/generic_signup_login.html" %}

{% block scripts %}
    {% load static %}
    <script src="{% static 'js/signup.js' %}"></script>
{% endblock %}

{% block content %}
    <h1>Sign Up</h1>

    <form id="signup-form" method="post"> {% csrf_token %}
        {% if err_list %}
        <div class="error-dialog">
            <ul>
            {% for error in err_list %}
                <li>{{ error }}</li>
            {% endfor %}
            </ul>
        </div>
        {% endif %}
        {{ form.as_p }}
        <button type="submit" value="Sign Up" class="submit-btn" id="submit-btn" onsubmit="event.preventDefault(); validate_signup_form()">Sign Up</button>
        <p style="text-align: center; color: white;">or <a id="f-link" href="{% url 'login' %}">log in</a> if you already have an account. </p>
    </form>
{% endblock %}

blog/templates/blog/signup2.html
{% extends "blog/generic_signup_login.html" %}

{% block content %}
    <h1>You're almost there!</h1>
    <form method="post"> {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Next" class="submit-btn">
    </form>
{% endblock %}